force-app/main/default/objects/Thread__c/fields/TAG_LastCachedTermsTime__c.field-meta.xml
<CustomField>
    <fullName>TAG_LastCachedTermsTime__c</fullName>
    <label>TAG_LastCachedTermsTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/TAG_LastCachedTermsUser__c.field-meta.xml
<CustomField>
    <fullName>TAG_LastCachedTermsUser__c</fullName>
    <label>TAG_LastCachedTermsUser</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/TAG_RelatedObjectExternalId__c.field-meta.xml
<CustomField>
    <fullName>TAG_RelatedObjectExternalId__c</fullName>
    <description>The external id for the related object record.</description>
    <label>TAG_RelatedObjectExternalId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmployerThreadDialogHelper.cls
public without sharing class EmployerThreadDialogHelper {
    private static final Integer CACHING_CALCULATION_TIME = -60;
    public static boolean isCacheExpired;

    @AuraEnabled(cacheable=true)
    public static boolean getCacheExpired(String agreementNumber, String userId) {
        try {
            Thread__c thread = getThread(agreementNumber);
            isCacheExpired = true;
            if (
                !cacheExpired(DateTime.valueOf(thread.TAG_LastCachedTermsTime__c)) &&
                thread.TAG_LastCachedTermsUser__c == userId
            ) {
                isCacheExpired = false;
            }
            return isCacheExpired ? false : true; //Terms accepted in LWC
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static void saveTermsAccepted(String contractNumber, String user) {
        try {
            Thread__c thread = getThread(contractNumber);
            thread.TAG_LastCachedTermsTime__c = DateTime.now();
            thread.TAG_LastCachedTermsUser__c = user;
            update thread;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static Thread__c getThread(String contractNr) {
        return [
            SELECT Id, TAG_LastCachedTermsUser__c, TAG_LastCachedTermsTime__c
            FROM Thread__c
            WHERE TAG_RelatedObjectExternalId__c = :contractNr
            LIMIT 1
        ];
    }

    private static boolean cacheExpired(DateTime lastCacheCalculation) {
        boolean expired = true;
        if (lastCacheCalculation > DateTime.now().addMinutes(CACHING_CALCULATION_TIME)) {
            expired = false;
        }
        return expired;
    }
}