force-app/main/default/objects/Thread__c/fields/TAG_RelatedObjectExternalId__c.field-meta.xml
<CustomField>
    <fullName>TAG_RelatedObjectExternalId__c</fullName>
    <description>The external id for the related object record.</description>
    <label>TAG_RelatedObjectExternalId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecordShareInitializerController.cls
public with sharing class RecordShareInitializerController {

    @AuraEnabled
    public static void calculateSharingForUser(String userId, String orgNumber) {
        if(!InputSanitizer.isValidRecordId(userId) || !InputSanitizer.isValidNorwegianOrgNumber(orgNumber)){
            throw new AuraHandledException('Invalid input format.');
        }
        try {
            EmployerThreadSharingService empThreadSharingService = new EmployerThreadSharingService();
            empThreadSharingService.calculateSharing(orgNumber, userId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String getAgreementThreadId(String agreementNumber) {
        if(!InputSanitizer.isValidContractExternalId(agreementNumber)){
            throw new AuraHandledException('Invalid input format.');
        }
        try {
            List<Thread__c> threads = [SELECT Id FROM Thread__c WHERE TAG_RelatedObjectExternalId__c = :agreementNumber LIMIT 1];
            SObjectAccessDecision decision = Security.stripInaccessible(AccessType.READABLE, threads);
            if(!decision.getModifiedIndexes().isEmpty()){
                throw new AuraHandledException('Permission denied');
            }
            return threads[0].Id;
        } catch (Exception e) {
            throw new AuraHandledException('Thread not found for agreement ' + agreementNumber);
        }
    }
}