force-app/main/default/objects/Contract__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Contract Id used in external systems.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/AG_LastRepresentedOrganization__c.field-meta.xml
<CustomField>
    <fullName>AG_LastRepresentedOrganization__c</fullName>
    <description>The organization number that the user last represented.</description>
    <label>AG_LastRepresentedOrganization</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrganizationBannerController.cls
public without sharing class OrganizationBannerController {
    @AuraEnabled(cacheable=true)
    public static Account getRepresentedOrganization(String userId) {
        try {
            String usersLastRepresentedOrganization = [
                SELECT AG_LastRepresentedOrganization__c
                FROM User
                WHERE Id = :userId
            ]
            ?.AG_LastRepresentedOrganization__c;

            Account account = [
                SELECT Name, INT_OrganizationNumber__c
                FROM Account
                WHERE INT_OrganizationNumber__c = :usersLastRepresentedOrganization
            ];

            return account;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Contract__c getContract(String contractNr) {
        return [SELECT id, TAG_ExternalURL__c, TAG_MeasureParticipant__c FROM Contract__c WHERE ExternalId__c = :contractNr];
    }

    @AuraEnabled(cacheable=true)
    public static Account getOrganization(String orgNumber) {
        return [SELECT id, INT_OrganizationNumber__c, Name FROM Account WHERE INT_OrganizationNumber__c = :orgNumber];
    }
}